### ISSUE TITLE
After adding the nuget package `services.AddSeoHelper();` not found

### ISSUE THREAD

**Issue by jeanpoelie** [sebnilsson/AspNetSeo#1]
After I added your package using Nuget, the package is recognised in the using statement but neither in aspnet core 2.2 or 3.0 I can use `services.AddSeoHelper();` in `Startup.cs`

**Comment by sebnilsson** [comment]
Is your project using any other target-framework than `netcoreapp2.0` or `netcoreapp3.0`?

My own website is running this with ASP.NET Core 3, so I can confirm this works.

**Comment by jeanpoelie** [comment]
I am running 3.0 as well, after removing all references and re-adding them it seems to be not an issue anymore.
As if something was wrong with caching or syntaxing.
