### ISSUE TITLE
OG meta tags

### ISSUE THREAD

**Issue by be4i** [sebnilsson/AspNetSeo#2]
Hello,

according to https://ogp.me the meta tags need to be with key "property" instead of "name".

**Comment by sebnilsson** [comment]
Great catch. Interesting that Facebook's validator/debug-page never flagged this problem for me.

**Comment by sebnilsson** [comment]
@be4i There is now a new version building out to NuGet:

https://www.nuget.org/packages/AspNetSeo.CoreMvc/1.2.0
